Dev
stepancar-web-programming/2023-fall-lab-portfolio-salnikov-g.-r. pull request #1
Opened 2023-11-14 21:24 UTC by goshik033

2024-01-04 04:27 UTC, stepancar commented
Здравствуйте, извините, почему-то пропустил ваш ПР.

2024-01-04 04:29 UTC, stepancar commented on libs/jquery/jquery-3.7.1.min.js
> +/*! jQuery v3.7.1 | (c) OpenJS Foundation and other contributors | jquery.org/license */
Для того, чтобы кодовая база была почище, предлагаю воспрользоваться публичным бесплатным cdn

2024-01-04 04:32 UTC, stepancar commented on css/hobbys.css
> +} */
Пожалуйста, подготовьте ПР к ревью

2024-01-04 04:33 UTC, stepancar commented on css/hobbys.css
> +
Пожалуйста, подготовьте код к ревью, избавьтесь от неконсистентности, лишнего кода

2024-01-04 04:34 UTC, stepancar commented on css/hobbys.css
> +    }
У вас прослеживается паттерн из BEM - если это он, не нужно ли состояние сделать модификатором?

2024-01-04 04:37 UTC, stepancar commented on hobbys.html
> +                    <p> +7(999)035-48-15</p>
Давайте сделаем так, чтобы при нажатии на телефон открывался стандартный диалог для звонка

2024-01-04 04:37 UTC, stepancar requested changes
Хорошая работа. Оставил замечания.

2024-01-09 07:58 UTC, goshik033 commented on css/hobbys.css
> +    }
Я не то чтобы строго придерживался этого подхода, но немножко он все-таки прослеживается. Модификатор я добавил

2024-01-09 07:58 UTC, goshik033 commented on hobbys.html
> +                    <p> +7(999)035-48-15</p>
Сделал

2024-01-09 07:58 UTC, goshik033 commented on css/hobbys.css
> +
Сделал

2024-01-09 07:58 UTC, goshik033 commented on css/hobbys.css
> +} */
Сделал

2024-01-09 07:58 UTC, goshik033 commented on libs/jquery/jquery-3.7.1.min.js
> +/*! jQuery v3.7.1 | (c) OpenJS Foundation and other contributors | jquery.org/license */
Сделал

2024-01-10 08:10 UTC, stepancar commented on js/hobbys.js
> +// });
Пожалуйста, убедитесь что, ПР готов к ревью, в нем есть все нужное и нет ничего не нужного

2024-01-10 08:12 UTC, stepancar commented on js/hobbys.js
> +});
Пожалуйста, добавьте линтеры, иначе мне придется оставить слишком много комментариев. Уважайте труд ревьюера, пользуйтесь автоматикой

2024-01-10 08:14 UTC, stepancar commented on js/hobbys.js
> +    console.log(parentElement)
```suggestion
```

2024-01-10 08:14 UTC, stepancar requested changes
Код не готов к ревью

2024-01-10 11:28 UTC, goshik033 commented on js/hobbys.js
> +// });
Сделал

2024-01-10 11:28 UTC, goshik033 commented on js/hobbys.js
> +});
Сделал

2024-01-10 11:28 UTC, goshik033 commented on js/hobbys.js
> +    console.log(parentElement)
Сделал

2024-01-11 07:42 UTC, stepancar commented on js/hobbys.js
> +});
@goshik033 , не вижу в проекте конфигов линтера

2024-01-11 07:47 UTC, stepancar requested changes
На странице по приложенной ссылке приложенной в ридми отличается код, от того что в репозитории

2024-01-11 12:36 UTC, goshik033 commented
Добавил новую ссылку

2024-01-16 07:59 UTC, stepancar commented on README.md
> +https://goshik033.github.io/2023-fall-lab-portfolio-salnikov-g.-r./
Обратите внимание на ползунок под видео. Справа от него время - текущий прогресс. Если вы попробуете медленно поперетягивать ползунок в конце видел - вы заметите что это работает иногда не корректно. Все дело в том, что прогресс влияет на ширину ползунка. Давайте исправим этот баг.

2024-01-16 08:00 UTC, stepancar commented on js/hobbys.js
> +  console.log(parentElement);
```suggestion
```

2024-01-16 08:03 UTC, stepancar commented on js/hobbys.js
> +playBtn.addEventListener("click", () => {
Заметьте, если включить музыку, потом видео - музыка продолжает играть. Давайте это исправим?

2024-01-16 08:03 UTC, stepancar commented on prof.html
> +            <h1>Тут как-то тихо..
Все еще впереди!

2024-01-16 08:06 UTC, stepancar commented
Оставил последние комментарии

2024-01-17 12:22 UTC, goshik033 commented on js/hobbys.js
> +playBtn.addEventListener("click", () => {
Исправлено

2024-01-17 12:23 UTC, goshik033 commented on js/hobbys.js
> +  console.log(parentElement);
Убрано

2024-01-17 12:23 UTC, goshik033 commented on README.md
> +https://goshik033.github.io/2023-fall-lab-portfolio-salnikov-g.-r./
Готово

2024-01-17 12:23 UTC, goshik033 commented on js/hobbys.js
> +});
Добавлено

2024-01-18 08:15 UTC, stepancar approved these changes

2024-01-18 08:16 UTC, merged